[package]
name = "chonker8"  
version = "8.30.0"
edition = "2021"
# Clean modular architecture - booyeeee!

[dependencies]
# Core
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "fs"] }
thiserror = "1.0"
bitflags = "2.4"
once_cell = "1.19"

# Terminal UI
crossterm = "0.28"

# PDF - Using ferrules for ML-powered extraction with internal PDFium
ferrules-core = { path = "ferrules/ferrules-core" }
pdfium-render = { version = "0.8", features = ["thread_safe"] }
image = "0.25"

# Image display in terminal
viuer = { version = "0.9.2", default-features = false }

# File picker
nucleo = "0.5"

# FAST clipboard
copypasta = "0.10"

# Basic utilities
lazy_static = "1.4"

# LANCE/VORTEX INTEGRATION - Week 1 (Mock implementation for now)
# TODO: Switch to real LanceDB when Arrow dependency conflicts are resolved
serde = { version = "1.0", optional = true }
bincode = { version = "1.3", optional = true }
chrono = { version = "0.4", optional = true }

# BAT/SYNTECT INTEGRATION - Week 4
syntect = { version = "5.0", optional = true }

# OPTIONAL ANALYTICS - Future
polars = { version = "0.35", optional = true }

[features]
default = []
lance-storage = ["serde", "bincode", "chrono"]
fancy-export = ["syntect"]
analytics = ["polars"]