[package]
name = "chonker8"  
version = "8.8.0"
edition = "2021"

[dependencies]
# Core CLI
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "fs"] }
thiserror = "1.0"
whatlang = "0.16"  # Language detection for gibberish detection

# PDF extraction
ferrules-core = { path = "ferrules/ferrules-core" }
pdfium-render = { version = "0.8", features = ["thread_safe"] }
# Note: Using pdftotext directly instead of extractous due to build issues

# Storage - Using rusqlite temporarily, will migrate to DuckDB once build issues resolved
rusqlite = { version = "0.32", features = ["bundled"] }
# duckdb = { version = "1.1", features = ["bundled", "vtab", "chrono"] }
chrono = "0.4"

[dev-dependencies]
rstest = "0.18"
rexpect = "0.5"

[features]
default = []
metal-accel = []
gpu-accel = []
hardware-accel = ["metal-accel", "gpu-accel"]