[package]
name = "chonker8"  
version = "8.6.0"
edition = "2021"

[dependencies]
# Core CLI
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "fs"] }
thiserror = "1.0"

# PDF extraction
ferrules-core = { path = "ferrules/ferrules-core" }
pdfium-render = { version = "0.8", features = ["thread_safe"] }

# Storage - Using rusqlite temporarily to get it compiled, will migrate back to DuckDB
rusqlite = { version = "0.32", features = ["bundled"] }
chrono = "0.4"

[features]
default = []
metal-accel = []
gpu-accel = []
hardware-accel = ["metal-accel", "gpu-accel"]