#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     CHONKER8 ADVANCED TEXT EDITOR DEMO                        ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║ NEW FEATURES:                                                 ║"
echo "║                                                                ║"
echo "║ Cut/Copy/Paste:                                               ║"
echo "║   • Ctrl+C: Copy selection to clipboard                       ║"
echo "║   • Ctrl+X: Cut selection to clipboard                        ║"
echo "║   • Ctrl+V: Paste from clipboard                              ║"
echo "║                                                                ║"
echo "║ Selection:                                                     ║"
echo "║   • Ctrl+A: Select all text                                   ║"
echo "║   • Ctrl+W: Select current word                               ║"
echo "║   • Ctrl+L: Select current line                               ║"
echo "║   • Shift+Arrows: Select text block                           ║"
echo "║                                                                ║"
echo "║ Navigation:                                                   ║"
echo "║   • Ctrl+Left/Right: Move by word                             ║"
echo "║   • Alt+Left/Right: Move to line start/end                    ║"
echo "║   • Ctrl+Up/Down: Move by paragraph                           ║"
echo "║                                                                ║"
echo "║ Editing:                                                       ║"
echo "║   • Ctrl+Z: Undo                                              ║"
echo "║   • Ctrl+Y or Ctrl+Shift+Z: Redo                              ║"
echo "║   • Ctrl+D: Duplicate current line                            ║"
echo "║   • Ctrl+S: Save to file                                      ║"
echo "║                                                                ║"
echo "║ Status bar shows operation feedback!                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Starting in 3 seconds..."
sleep 3

# Run with test UI mode
./target/release/chonker8-hot --test-ui "$@"